name: Build and Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'  

      - name: Install Dependencies
        run: npm i plivo-browser-sdk@2.2.10-beta.5

      - name: Build
        run: npm run build